#!/bin/sh
set -e

# Create a symlink to kafka config in kafka distribution folder
if [ ! -e "/opt/kafka/config" ]; then
    ln -s /opt/kafka/config /etc/kafka
fi

# Create a directory to store working data
#mkdir -p /var/run/kafka
#chown -R kafka:kafka /var/run/kafka

# Create a directory for logs
#chown -R kafka:kafka /var/log/kafka

# Set permissions on directories
/bin/chown -R kafka:kafka /opt/kafka /var/log/kafka /var/lib/kafka

#DEBHELPER#

[ "$1" = "configure" ] && ldconfig

exit 0
